### ISSUE TITLE
Decide on licenses for content/software

### ISSUE THREAD

**Issue by colliand** [jack-eddy-symposium/meta#2]
Some interactive content will be shared publicly using this organization. How should the content be licensed? 

Here is the [GitHub page on licenses](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository). As a default, shall we proceed with cc-by-4?

**Comment by rmcgranaghan** [comment]
thanks for thinking about this, Jim. Was questioning it myself. 

In the ethos of openness, I think CC-BY-4.0 is a good choice. Welcome to other opinions, of course. @dan800 - do you see any issue with that?

**Comment by dan800** [comment]
I am happy to go with cc-by-4. This might be a good topic for discussion and/or tutorial -- those new to writing open source code would probably benefit from hearing the pros and cons of various licenses and how to make it clear what license is being used. Could be covered in an afternoon coffee break.

**Comment by colliand** [comment]
I've added cc-by-4 license files and copied the same text at the top of the README file in the current collection of repos.
